$image = /home/quantum/Pictures/Wallpapers/82054.jpg

$background = rgba(171217ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(342f34ff)

$inverse_primary = rgba(7a4e80ff)

$inverse_surface = rgba(eadfe6ff)

$on_background = rgba(eadfe6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(48204fff)

$on_primary_container = rgba(ffd6ffff)

$on_primary_fixed = rgba(300938ff)

$on_primary_fixed_variant = rgba(613767ff)

$on_secondary = rgba(3b2b3cff)

$on_secondary_container = rgba(f4dbf2ff)

$on_secondary_fixed = rgba(251726ff)

$on_secondary_fixed_variant = rgba(524153ff)

$on_surface = rgba(eadfe6ff)

$on_surface_variant = rgba(d0c3ccff)

$on_tertiary = rgba(4c2520ff)

$on_tertiary_container = rgba(ffdad5ff)

$on_tertiary_fixed = rgba(33110dff)

$on_tertiary_fixed_variant = rgba(673b35ff)

$outline = rgba(998d96ff)

$outline_variant = rgba(4d444cff)

$primary = rgba(eab5eeff)

$primary_container = rgba(613767ff)

$primary_fixed = rgba(ffd6ffff)

$primary_fixed_dim = rgba(eab5eeff)

$scrim = rgba(000000ff)

$secondary = rgba(d7bfd5ff)

$secondary_container = rgba(524153ff)

$secondary_fixed = rgba(f4dbf2ff)

$secondary_fixed_dim = rgba(d7bfd5ff)

$shadow = rgba(000000ff)

$source_color = rgba(907491ff)

$surface = rgba(171217ff)

$surface_bright = rgba(3d373dff)

$surface_container = rgba(231e23ff)

$surface_container_high = rgba(2e282dff)

$surface_container_highest = rgba(393338ff)

$surface_container_low = rgba(1f1a1fff)

$surface_container_lowest = rgba(110d11ff)

$surface_dim = rgba(171217ff)

$surface_tint = rgba(eab5eeff)

$surface_variant = rgba(4d444cff)

$tertiary = rgba(f6b8afff)

$tertiary_container = rgba(673b35ff)

$tertiary_fixed = rgba(ffdad5ff)

$tertiary_fixed_dim = rgba(f6b8afff)
