-- Optional marker to suppress autogenerated warning
hl.config({
    autogenerated = false,
})

-- Load modules
require("config.screen")
require("config.autostart")

-- Core configs
require("config.environment")
require("config.window")
require("config.decoration")
require("config.layout")
require("config.keybinding")

-- Animations
require("config.animation")

