general {
    disable_loading_bar = true
    grace = 2
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 48
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 300, 60
    outline_thickness = 2

    outer_color = rgba(255,255,255,0.2)
    inner_color = rgba(0,0,0,0.3)
    font_color = rgb(255,255,255)

    fade_on_empty = false
    hide_input = false

    # zamiast kropek pokaż gwiazdki
    dots_text_format = *

    position = 0, -40
    halign = center
    valign = center
}
